PATTERNS = {
    "mediqa": [
        ("dialogue:\n{dialogue}\n\nGenerate {section_header} section of the medical note from dialogue.", "{section_text}"),
        ("dialogue:\n{dialogue}\n\nsummarize {section_header} section of the medical note from dialogue.", "{section_text}"),
        ("Patient doctor dialogue:\n{dialogue}\n\nWhat is {section_header} of the medical note?", "{section_text}"),
        ("summarize medical note with important medical concept.\n\n{dialogue}", "{section_text}"),
        ("Write a patient doctor dialog with this premise \"{section_text}\" from {section_header} of the medical note.", "{dialogue}"),
        ("{section_header} section of the medical note: {section_text}\n\nGenerate a dialog of this note.","{dialogue}"),
        ("{section_header} section of the medical note: {section_text}\n\nWrite a dialog of this note.","{dialogue}"),
        ("Write a dialogue given \"{section_text}\".", "{dialogue}"),
    ],
    "mediqa_finetune": [
        ("dialogue:\n{dialogue}\n\nGenerate {section_header} section of the medical note from dialogue.", "{section_text}"),
    ],
    "mediqa_predict": [
        ("dialogue:\n{dialogue}\n\nGenerate {section_header} section of the medical note from dialogue.", "{section_text}"),
    ],
    "dart": [
        ("Concepts: {tripleset}\n\nWhat is a sentence that describes this concepts?", "{target}"),
        ("Here is some triplet data: {tripleset}.\n\nWrite a sentence that describes this data", "{target}"),
        ("What concepts are described in the following sentence?\n\n\"{target}\"\n\nReturn the answer as pairs of triples.", "{tripleset}"),
    ],
    "cosmos_qa": [
       ("{context}\n\nBased on the preceding passage, answer the following question {question} with following options\n{options}", "{answer_true}"),
       ("{context}\n\nAnswer the following question: {question}", "{answer_true}"),
       ("Context: {context}\nQuestion: {question}\nOptions: {options}\nAnswer:", "{answer_true}"),
       ("Write a question about the context\n\n{context}", "{question}"),
    ],
    "medmcqa": [
        ("Medical note context and question: {question}\nOptions: {options}\nExplain: {exp}\n\nAnswer:", "{ans}"),
        ("Medical note context and question: {question}\nExplain: {exp}\n\nAnswer:", "{ans}"),
        ("Medical note context and question: {question}\n\nAnswer:", "{ans}"),
        ("Medical note context and question: {question}\nOptions: {options}\nExplain: ", "{exp}\n\nAnswer: {ans}"),
    ],
    "usmleqa": [
        ("Medical note context and question: {question}\nOptions: {options}\n\nAnswer:", "{ans}")
    ],
    "mednli": [
        ("Premise: {sentence1}\n\nHypothesis: {sentence2}\n\nIn clinical context, does the premise "
         "entail the hypothesis?\n\n{options_}", "{gold_label}"),
        ("Premise: {sentence1}\nHypothesis: {sentence2}\nIs the hypothesis "
         "entailed by the premise in medical context?\n{options_}", "{gold_label}"),
        ("Here is a premise:\n{sentence1}\n\nHere is a "
         "hypothesis:\n{sentence2}\n\nIs it possible to conclude that if the "
         "premise is true, then so is the hypothesis?\n{options_}", "{gold_label}"),
        ("Sentence 1: {sentence1}\n\nSentence 2: {sentence2}\nIs this second "
         "sentence entailed by the first sentence?\n\n{options_}", "{gold_label}"),
        ("Sentence 1: {sentence1}\n\nSentence 2: {sentence2}\n\nIf the first "
         "sentence is true, then is the second sentence clinically true?\n{options_}",
         "{gold_label}"),
        ("Premise:\n\"{sentence1}\" Based on this premise, is the hypothesis "
         "\"{sentence2}\" true in clinical context?\n{options_}", "{gold_label}"),
        ("If {sentence1}, can we conclude that \"{sentence2}\"?\n{options_}",
         "{gold_label}"),
        ("{sentence1}\n\nDoes it follow that \"{sentence2}\"?\n{options_}",
         "{gold_label}"),
    ],
    "meqsum": [
        ("{note}\n\nBriefly summarize that medical note to dialogue question.", "{summary}"),
        ("Medical note:\n{note}\n\nWhat is a summary of this note?", "{summary}"),
        ("Write a medical note based on this dialogue question:\n{summary}.", "{note}"),
        ("Write a medical note with this premise \"{summary}\".", "{note}"),
    ],
    "taskmasters": [
        ("{dialoguestr}\n\nsummarize the dialogue into important concepts.", "{conceptstr}"),
        ("dialogue:\n{dialoguestr}\n\nWhat is a summary of this dialogue?", "{conceptstr}"),
        ("Write a user system dialog with this premise below:\n{conceptstr}", "{dialoguestr}"),
    ],
    "wiki_lingua": [
        ("summarize:\n{source}", "{target}"),
    ],
    "wsc": [
        ("{text}\n\nAre \"{span1_text}\" and \"{span2_text}\" the same entity?", "{label_text}"),
        ("{text}\n\nDo \"{span1_text}\" and \"{span2_text}\" have the same meaning?", "{label_text}"),
        ("Given the following context\n\n{text}\n\nAre \"{span1_text}\" and \"{span2_text}\" the same?", "{label_text}"),
        ("{text}\n\nDo \"{span2_text}\" and \"{span1_text}\" mean the same thing?", "{label_text}"),
    ],
    "emrqa_smoking": [
        ("{note}\nGenerate some medically significant questions and answers about smoking for this note:",
         "{questions_answers}"),
        ("{note}\nWhat's the medically significant questions and answers about smoking for this note?",
         "{questions_answers}"),
        ("{note}\n\nPlease generate some medically significant questions and answers about smoking.", 
         "{questions_answers}"),
        ("generate some medically significant questions and answers about smoking for this note: {note}", "{questions_answers}"),
        ("We need some medically significant questions and answers about smoking for this note, please generate them: {note}",
         "{questions_answers}"),
        ("Generate some medically significant questions and answers about smoking in the following note: {note}",
         "{questions_answers}"),
        ("Write all the medically significant questions and answers about smoking in this note: {note}", 
         "{questions_answers}"),
        ("According to the following questions and answers about smoking, please generate a reasonable clinical note: {questions_answers}",
         "{note}"),
        ("Some questions and answers about smoking: {questions_answers}. What's the reasonable clinical note for these questions and answers about smoking?",
         "{note}"),
        ("{questions_answers} Please imagine a suitable clinical note for the above questions and answers about smoking. ", 
         "{note}"),
    ],
    "emrqa_relations": [
        ("{context}\nGenerate some medically significant questions for this context:",
         "{questions}"),
        ("{context}\nWhat's the medically significant questions for this context?",
         "{questions}"),
        ("{context}\n\nPlease generate some medically significant questions.", 
         "{questions}"),
        ("generate some medically significant questions for this context: {context}", "{questions}"),
        ("We need some medically significant questions for this context, please generate them: {context}",
         "{questions}"),
        ("Generate some medically significant questions in the following context: {context}",
         "{questions}"),
        ("Write all the medically significant questions in this context: {context}", 
         "{questions}"),
        ("According to the following questions, please generate a reasonable clinical context: {questions}",
         "{context}"),
        ("Some questions: {questions}. What's the reasonable clinical context for these questions?",
         "{context}"),
        ("{questions} Please imagine a suitable clinical context for the above questions. ", 
         "{context}"),
    ],
    "emrqa_obesity": [
        ("{note}\nGenerate some medically significant questions and answers about obesity for this note:",
         "{questions_answers}"),
        ("{note}\nWhat's the medically significant questions and answers about obesity for this note?",
         "{questions_answers}"),
        ("{note}\n\nPlease generate some medically significant questions and answers about obesity.", 
         "{questions_answers}"),
        ("generate some medically significant questions and answers about obesity for this note: {note}", "{questions_answers}"),
        ("We need some medically significant questions and answers about obesity for this note, please generate them: {note}",
         "{questions_answers}"),
        ("Generate some medically significant questions and answers about obesity in the following note: {note}",
         "{questions_answers}"),
        ("Write all the medically significant questions and answers about obesity in this note: {note}", 
         "{questions_answers}"),
        ("According to the following questions and answers about obesity, please generate a reasonable clinical note: {questions_answers}",
         "{note}"),
        ("Some questions and answers about obesity: {questions_answers}. What's the reasonable clinical note for these questions and answers about obesity?",
         "{note}"),
        ("{questions_answers} Please imagine a suitable clinical note for the above questions and answers about obesity. ", 
         "{note}"),
    ],
    "emrqa_medication": [
        ("{context}\nGenerate some medically significant questions and answers about medication for this context:",
         "{questions_answers}"),
        ("{context}\nWhat's the medically significant questions and answers about medication for this context?",
         "{questions_answers}"),
        ("{context}\n\nPlease generate some medically significant questions and answers about medication.", 
         "{questions_answers}"),
        ("generate some medically significant questions and answers about medication for this context: {context}", "{questions_answers}"),
        ("We need some medically significant questions and answers about medication for this context, please generate them: {context}",
         "{questions_answers}"),
        ("Generate some medically significant questions and answers about medication in the following context: {context}",
         "{questions_answers}"),
        ("Write all the medically significant questions and answers about medication in this context: {context}", 
         "{questions_answers}"),
        ("According to the following questions and answers about medication, please generate a reasonable clinical context: {questions_answers}",
         "{context}"),
        ("Some questions and answers about medication: {questions_answers}. What's the reasonable clinical context for these questions and answers about medication?",
         "{context}"),
        ("{questions_answers} Please imagine a suitable clinical context for the above questions and answers about medication. ", 
         "{context}"),
    ],
    "discq": [
        ("{note}\nGenerate some medically significant questions for this note:",
         "{questions}"),
        ("{note}\nWhat's the medically significant questions for this note?",
         "{questions}"),
        ("{note}\n\nPlease generate some medically significant questions.", 
         "{questions}"),
        ("generate some medically significant questions for this note: {note}", "{questions}"),
        ("We need some medically significant questions for this note, please generate them: {note}",
         "{questions}"),
        ("Generate some medically significant questions in the following note: {note}",
         "{questions}"),
        ("Write all the medically significant questions in this note: {note}", 
         "{questions}"),
        ("According to the following questions, please generate a reasonable clinical note: {questions}",
         "{note}"),
        ("Some questions from phycisians: {questions}. What's the reasonable clinical note for these questions?",
         "{note}"),
        ("{questions} Please imagine a suitable clinical notes for the above questions. ", 
         "{note}"),
    ],
    "diagnoise-me": [
        ("Answer patient's question step by step.\n\nQuestion: {question}.\n\nAnswer: ", "{CoT_answer}"),
        ("Summarize the patient question: {question}", "{question_summry}"),
        ("Patient: {question_summry}\nDoctor: Can you elaborate on the situation regarding your issue?\nPatient: Sure. ", "{question}"),
        ("Patient: {question_summry}\nDoctor: Can you tell me more?\nPatient: Yes. {question}\nDoctor: ", "{CoT_answer}"),
    ],
    "samsum": [
        ("Dialogue:\n{dialogue}\n\nGenerate summary from dialogue.", "{summary}"),
        ("What is the summary of this dialogue?\n\n{dialogue}", "{summary}"),
        ("Conversation:\n{dialogue}\n\n Given this conversation, we can infer this conclusion.", "{summary}"),
        ("Write a dialogue relevant to this passage. \n\n{summary}", "{dialogue}"),
        ("Summary:\n{summary}\n\nGenerate a conversation relevant to the summary.", "{dialogue}"),
        ("Considering this conclusion, two people had this conversation. \n\n{summary}", "{dialogue}"),
    ],
    "mediqasum": [
        ("Message:\n{message}\n\nGenerate medical question from message.", "{question}"),
        ("What is the medical question in this message?\n\n{message}", "{question}"),
        ("Message:\n{message}\n\n Given this message, what medical question can be asked?", "{question}"),
        ("Message:\n{message}\n\n What is the patient asking in this message?", "{question}"),
        ("Write a message relevant to this question. \n\n{question}", "{message}"),
        ("Medical Question:\n{question}\n\nGenerate a message relevant to the question.", "{message}"),
        ("Medical Question:\n{question}\n\nGenerate a message from a patient asking this question.", "{message}"),
        ("A doctor was asked {question}. Generate the message from the patient", "{message}"),
    ],
    "pmc-patient": [
        ("Given patient medical note {input} {output}\nSummarize the title of this note", "{title}"),
        ("medical note: {input}", "{output}"),
        ("Given patient medical note {input}\nWhat is the age of this patient?", "{age}")
    ],
    "mimic_section": [
        ("{input}", "{output}")
    ],


}

